// swift-tools-version: 5.9
import PackageDescription
import Foundation

let packageRoot = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
for generatedArtifact in ["Resources/worklet.bundle", "Resources/worklet-manifest.json"] {
    guard FileManager.default.fileExists(atPath: packageRoot.appendingPathComponent(generatedArtifact).path) else {
        fatalError("Missing generated iOS artifact \(generatedArtifact). Run `npm run setup` at the repository root.")
    }
}

// The addon xcframeworks are generated by `bare-link --preset ios` (npm run
// setup) and are gitignored, so a fresh clone must run it before this package
// resolves. The version suffixes are part of the directory names, and the JS
// bundle references them BY VERSION (`linked:sodium-native.5.1.0.framework/...`
// is baked into worklet.bundle). If this list drifts from ls Addons/*.xcframework
// you get a clean resolve error; if it drifts from the bundle you get a *runtime*
// "No addon registered". Always `npm run setup`, never `npm run link` alone.
let addons = [
    "bare-buffer.3.6.0",
    "bare-crypto.1.13.4",
    "bare-fs.4.5.6",
    "bare-inspect.3.1.4",
    "bare-os.3.8.2",
    "bare-pipe.4.1.5",
    "bare-structured-clone.1.5.3",
    "bare-type.1.1.0",
    "bare-url.2.4.0",
    "fs-native-extensions.1.4.5",
    "quickbit-native.2.4.8",
    "rocksdb-native.3.15.0",
    "simdle-native.1.3.9",
    "sodium-native.5.1.0",
    "udx-native.1.19.2"
]

// Nothing in Swift imports the addons — they export only
// `bare_register_module_v0`, and Bare finds them by walking the loaded dyld
// images at runtime. They must still be listed as dependencies: linking is what
// puts them in the image list. "Embed but don't link" fails at runtime, not at
// build time.
let package = Package(
    name: "ZappMessaging",
    platforms: [.iOS(.v16)],
    products: [
        .library(name: "ZappMessaging", targets: ["ZappMessaging"])
    ],
    targets: [
        .target(
            name: "ZappMessaging",
            dependencies: [.target(name: "BareKit")] + addons.map { .target(name: $0) },
            path: ".",
            exclude: [
                "Addons",
                "Frameworks",
                "Tests",
                "build",
                "project.yml",
                "README.md",
                "ZappMessaging.xcodeproj",
                ".DS_Store",
                "Resources/.DS_Store"
            ],
            sources: ["Sources/ZappMessaging"],
            resources: [
                .copy("Resources/worklet.bundle"),
                .copy("Resources/worklet-manifest.json")
            ]
        ),
        .binaryTarget(name: "BareKit", path: "Frameworks/BareKit.xcframework")
    ] + addons.map { .binaryTarget(name: $0, path: "Addons/\($0).xcframework") }
)
